name: Deploy to PyPI

on:
  push:
    tags: 
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Poetry
        run: curl -sL https://install.python-poetry.org | python - -y
      - name: Install poetry dependencies & create virtualenv
        run: poetry install
      - name: Publish to PyPI
        run: |
          poetry config http-basic.pypi "__token__" "${{ secrets.PYPI_TOKEN }}"	
          poetry publish --build