name: Tests
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        poetry-version: [1.0, 1.1.11]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install poetry dependencies & create virtualenv
        run: poetry install
      - name: Run Tests
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          MONDAY_TESTING_BOARD_ID: ${{ secrets.MONDAY_TESTING_BOARD_ID }}
        run: poetry run pytest tests
